function Get-AxDefaultStubRules {
    [CmdletBinding()]
    param()

    @(
        New-AxAssessmentRule -RuleId 'M365-001' -Name 'Baseline Graph Connectivity Rule' -AssessmentPack 'Microsoft365' -Service 'Microsoft 365' -Description 'Stub rule for connector-backed assessment flow.' -DefaultSeverity 'Medium' -Evaluate {
            param($Context)

            New-AxFinding -FindingId 'AX-M365-001' `
                -Category 'Identity' `
                -Service 'Microsoft 365' `
                -Scope ($Context.Scope ?? 'Tenant') `
                -Severity 'Medium' `
                -Likelihood 'Medium' `
                -Impact 'High' `
                -Title 'Stub Microsoft 365 finding' `
                -Description 'Generated by the Phase 04 assessment orchestrator stub rule.' `
                -Evidence @([pscustomobject]@{ Source = 'StubDataset'; Reference = 'Graph/TenantSummary'; Value = 'SampleEvidence' }) `
                -Recommendation 'Replace stub rule logic with real Microsoft 365 assessment checks in Phase 05.' `
                -RemediationType 'Configuration' `
                -FrameworkMappings @([pscustomobject]@{ Framework = 'NIS2'; Control = 'AccessControl' }) `
                -Source @{ Connector = 'MicrosoftGraph'; RuleId = 'M365-001'; Pack = 'Microsoft365' }
        }
        New-AxAssessmentRule -RuleId 'AZ-001' -Name 'Baseline Azure Connectivity Rule' -AssessmentPack 'Azure' -Service 'Azure' -Description 'Stub rule for Azure assessment flow.' -DefaultSeverity 'Low' -Evaluate {
            param($Context)

            New-AxFinding -FindingId 'AX-AZ-001' `
                -Category 'Governance' `
                -Service 'Azure' `
                -Scope ($Context.Scope ?? 'Subscription') `
                -Severity 'Low' `
                -Likelihood 'Low' `
                -Impact 'Medium' `
                -Title 'Stub Azure finding' `
                -Description 'Generated by the Phase 04 assessment orchestrator stub rule.' `
                -Evidence @([pscustomobject]@{ Source = 'StubDataset'; Reference = 'Azure/SubscriptionSummary'; Value = 'SampleEvidence' }) `
                -Recommendation 'Replace stub rule logic with real Azure assessment checks in Phase 06.' `
                -RemediationType 'Configuration' `
                -FrameworkMappings @([pscustomobject]@{ Framework = 'ISO27001'; Control = 'A.5' }) `
                -Source @{ Connector = 'Azure'; RuleId = 'AZ-001'; Pack = 'Azure' }
        }
    )
}
