function Get-AxExecutiveSummaryMarkdown {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [psobject[]]$Finding,

        [Parameter()]
        [psobject[]]$RiskRegister = @(),

        [Parameter()]
        [psobject[]]$Scorecard = @()
    )

    $template = Get-AxReportTemplate -TemplateName 'executive-summary'
    $scope = Get-AxReportScopeSummary -Finding $Finding
    $topDomains = @($Scorecard | Sort-Object Score | Select-Object -First 3)
    $topFindings = @($Finding | Sort-Object RiskScore -Descending | Select-Object -First 3)
    $highRisk = @(
        $Finding | Where-Object {
            (Get-AxSeverityDefinition -Severity ([string]$_.Severity)).label -in @('High', 'Critical')
        }
    ).Count

    $lines = @(
        "# $($template.reportTitle)",
        '',
        "## $(Get-AxTemplateSectionTitle -SectionKey 'report_title_and_metadata')",
        "- Output name: $($template.outputBaseName)",
        "- Audience: $($template.audience)",
        "- Generated by: AuditXpert_GPT reporting module",
        '',
        "## $(Get-AxTemplateSectionTitle -SectionKey 'scope')",
        "- Services: $($scope.ServiceSummary)",
        "- Scope references: $($scope.ScopeSummary)",
        '',
        "## $(Get-AxTemplateSectionTitle -SectionKey 'methodology')",
        '- This report is generated from normalized findings and available governance outputs.',
        '- Severity language follows the controlled reporting standard.',
        '',
        "## $(Get-AxTemplateSectionTitle -SectionKey 'executive_summary')",
        "Total findings: $($Finding.Count)",
        "High or critical findings: $highRisk",
        "Risk register items: $($RiskRegister.Count)",
        'Priority message: address critical and high-severity items first, then schedule medium and low-severity improvements through a tracked remediation plan.',
        '',
        "## $(Get-AxTemplateSectionTitle -SectionKey 'risk_overview')"
    )

    $severityGroups = $Finding |
        Group-Object { (Get-AxSeverityDefinition -Severity ([string]$_.Severity)).label } |
        Sort-Object Name

    foreach ($group in $severityGroups) {
        $severityDefinition = Get-AxSeverityDefinition -Severity ([string]$group.Name)
        $lines += "- $($severityDefinition.label): $($group.Count) finding(s), priority $($severityDefinition.priority)"
    }

    $lines += ''
    $lines += "## $(Get-AxTemplateSectionTitle -SectionKey 'key_findings')"
    foreach ($item in $topFindings) {
        $severityDefinition = Get-AxSeverityDefinition -Severity ([string]$item.Severity)
        $lines += "- [$($item.FindingId)] $($item.Title) ($($severityDefinition.label)) in $($item.Scope)"
    }

    $lines += ''
    $lines += "## $(Get-AxTemplateSectionTitle -SectionKey 'recommendations')"
    foreach ($item in $topFindings) {
        $lines += "- [$($item.FindingId)] $($item.Recommendation)"
    }

    $lines += ''
    $lines += "## $(Get-AxTemplateSectionTitle -SectionKey 'compliance_control_mapping')"
    if ($topDomains.Count -gt 0) {
        foreach ($domain in $topDomains) {
            $lines += "- $($domain.Domain): score $($domain.Score), maturity $($domain.Maturity)"
        }
    }
    else {
        $lines += '- Governance scorecard data was not provided for this report run.'
    }

    $lines += ''
    $lines += "## $(Get-AxTemplateSectionTitle -SectionKey 'evidence_appendix')"
    $lines += '- Every recommendation above should be traced back to the related FindingId in the technical report.'
    $lines += '> AI-assisted narrative, if enabled later, must remain traceable to finding IDs and is not evidence.'
    $lines -join [Environment]::NewLine
}
